package eu.darken.butler.common.theming

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

object ThemeColorProvider {

    fun getLightColorScheme(color: ThemeColor, style: ThemeStyle): ColorScheme {
        return when (color) {
            ThemeColor.GREEN -> when (style) {
                ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> getGreenLightScheme()
                ThemeStyle.MEDIUM_CONTRAST -> getGreenMediumContrastLightScheme()
                ThemeStyle.HIGH_CONTRAST -> getGreenHighContrastLightScheme()
            }
            ThemeColor.BLUE -> when (style) {
                ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> getBlueLightScheme()
                ThemeStyle.MEDIUM_CONTRAST -> getBlueMediumContrastLightScheme()
                ThemeStyle.HIGH_CONTRAST -> getBlueHighContrastLightScheme()
            }
            ThemeColor.AMOLED -> when (style) {
                ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> getAmoledLightScheme()
                ThemeStyle.MEDIUM_CONTRAST -> getAmoledMediumContrastLightScheme()
                ThemeStyle.HIGH_CONTRAST -> getAmoledHighContrastLightScheme()
            }
        }
    }

    fun getDarkColorScheme(color: ThemeColor, style: ThemeStyle): ColorScheme {
        return when (color) {
            ThemeColor.GREEN -> when (style) {
                ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> getGreenDarkScheme()
                ThemeStyle.MEDIUM_CONTRAST -> getGreenMediumContrastDarkScheme()
                ThemeStyle.HIGH_CONTRAST -> getGreenHighContrastDarkScheme()
            }
            ThemeColor.BLUE -> when (style) {
                ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> getBlueDarkScheme()
                ThemeStyle.MEDIUM_CONTRAST -> getBlueMediumContrastDarkScheme()
                ThemeStyle.HIGH_CONTRAST -> getBlueHighContrastDarkScheme()
            }
            ThemeColor.AMOLED -> when (style) {
                ThemeStyle.DEFAULT, ThemeStyle.MATERIAL_YOU -> getAmoledDarkScheme()
                ThemeStyle.MEDIUM_CONTRAST -> getAmoledMediumContrastDarkScheme()
                ThemeStyle.HIGH_CONTRAST -> getAmoledHighContrastDarkScheme()
            }
        }
    }

    // Green color schemes
    private fun getGreenLightScheme() = lightColorScheme(
        primary = ButlerColorsGreen.primaryLight,
        onPrimary = ButlerColorsGreen.onPrimaryLight,
        primaryContainer = ButlerColorsGreen.primaryContainerLight,
        onPrimaryContainer = ButlerColorsGreen.onPrimaryContainerLight,
        secondary = ButlerColorsGreen.secondaryLight,
        onSecondary = ButlerColorsGreen.onSecondaryLight,
        secondaryContainer = ButlerColorsGreen.secondaryContainerLight,
        onSecondaryContainer = ButlerColorsGreen.onSecondaryContainerLight,
        tertiary = ButlerColorsGreen.tertiaryLight,
        onTertiary = ButlerColorsGreen.onTertiaryLight,
        tertiaryContainer = ButlerColorsGreen.tertiaryContainerLight,
        onTertiaryContainer = ButlerColorsGreen.onTertiaryContainerLight,
        error = ButlerColorsGreen.errorLight,
        onError = ButlerColorsGreen.onErrorLight,
        errorContainer = ButlerColorsGreen.errorContainerLight,
        onErrorContainer = ButlerColorsGreen.onErrorContainerLight,
        background = ButlerColorsGreen.backgroundLight,
        onBackground = ButlerColorsGreen.onBackgroundLight,
        surface = ButlerColorsGreen.surfaceLight,
        onSurface = ButlerColorsGreen.onSurfaceLight,
        surfaceVariant = ButlerColorsGreen.surfaceVariantLight,
        onSurfaceVariant = ButlerColorsGreen.onSurfaceVariantLight,
        outline = ButlerColorsGreen.outlineLight,
        outlineVariant = ButlerColorsGreen.outlineVariantLight,
        scrim = ButlerColorsGreen.scrimLight,
        inverseSurface = ButlerColorsGreen.inverseSurfaceLight,
        inverseOnSurface = ButlerColorsGreen.inverseOnSurfaceLight,
        inversePrimary = ButlerColorsGreen.inversePrimaryLight,
    )

    private fun getGreenDarkScheme() = darkColorScheme(
        primary = ButlerColorsGreen.primaryDark,
        onPrimary = ButlerColorsGreen.onPrimaryDark,
        primaryContainer = ButlerColorsGreen.primaryContainerDark,
        onPrimaryContainer = ButlerColorsGreen.onPrimaryContainerDark,
        secondary = ButlerColorsGreen.secondaryDark,
        onSecondary = ButlerColorsGreen.onSecondaryDark,
        secondaryContainer = ButlerColorsGreen.secondaryContainerDark,
        onSecondaryContainer = ButlerColorsGreen.onSecondaryContainerDark,
        tertiary = ButlerColorsGreen.tertiaryDark,
        onTertiary = ButlerColorsGreen.onTertiaryDark,
        tertiaryContainer = ButlerColorsGreen.tertiaryContainerDark,
        onTertiaryContainer = ButlerColorsGreen.onTertiaryContainerDark,
        error = ButlerColorsGreen.errorDark,
        onError = ButlerColorsGreen.onErrorDark,
        errorContainer = ButlerColorsGreen.errorContainerDark,
        onErrorContainer = ButlerColorsGreen.onErrorContainerDark,
        background = ButlerColorsGreen.backgroundDark,
        onBackground = ButlerColorsGreen.onBackgroundDark,
        surface = ButlerColorsGreen.surfaceDark,
        onSurface = ButlerColorsGreen.onSurfaceDark,
        surfaceVariant = ButlerColorsGreen.surfaceVariantDark,
        onSurfaceVariant = ButlerColorsGreen.onSurfaceVariantDark,
        outline = ButlerColorsGreen.outlineDark,
        outlineVariant = ButlerColorsGreen.outlineVariantDark,
        scrim = ButlerColorsGreen.scrimDark,
        inverseSurface = ButlerColorsGreen.inverseSurfaceDark,
        inverseOnSurface = ButlerColorsGreen.inverseOnSurfaceDark,
        inversePrimary = ButlerColorsGreen.inversePrimaryDark,
    )

    private fun getGreenMediumContrastLightScheme() = lightColorScheme(
        primary = ButlerColorsGreen.primaryLightMediumContrast,
        onPrimary = ButlerColorsGreen.onPrimaryLightMediumContrast,
        primaryContainer = ButlerColorsGreen.primaryContainerLightMediumContrast,
        onPrimaryContainer = ButlerColorsGreen.onPrimaryContainerLightMediumContrast,
        secondary = ButlerColorsGreen.secondaryLightMediumContrast,
        onSecondary = ButlerColorsGreen.onSecondaryLightMediumContrast,
        secondaryContainer = ButlerColorsGreen.secondaryContainerLightMediumContrast,
        onSecondaryContainer = ButlerColorsGreen.onSecondaryContainerLightMediumContrast,
        tertiary = ButlerColorsGreen.tertiaryLightMediumContrast,
        onTertiary = ButlerColorsGreen.onTertiaryLightMediumContrast,
        tertiaryContainer = ButlerColorsGreen.tertiaryContainerLightMediumContrast,
        onTertiaryContainer = ButlerColorsGreen.onTertiaryContainerLightMediumContrast,
        error = ButlerColorsGreen.errorLightMediumContrast,
        onError = ButlerColorsGreen.onErrorLightMediumContrast,
        errorContainer = ButlerColorsGreen.errorContainerLightMediumContrast,
        onErrorContainer = ButlerColorsGreen.onErrorContainerLightMediumContrast,
        background = ButlerColorsGreen.backgroundLightMediumContrast,
        onBackground = ButlerColorsGreen.onBackgroundLightMediumContrast,
        surface = ButlerColorsGreen.surfaceLightMediumContrast,
        onSurface = ButlerColorsGreen.onSurfaceLightMediumContrast,
        surfaceVariant = ButlerColorsGreen.surfaceVariantLightMediumContrast,
        onSurfaceVariant = ButlerColorsGreen.onSurfaceVariantLightMediumContrast,
        outline = ButlerColorsGreen.outlineLightMediumContrast,
        outlineVariant = ButlerColorsGreen.outlineVariantLightMediumContrast,
        scrim = ButlerColorsGreen.scrimLightMediumContrast,
        inverseSurface = ButlerColorsGreen.inverseSurfaceLightMediumContrast,
        inverseOnSurface = ButlerColorsGreen.inverseOnSurfaceLightMediumContrast,
        inversePrimary = ButlerColorsGreen.inversePrimaryLightMediumContrast,
    )

    private fun getGreenMediumContrastDarkScheme() = darkColorScheme(
        primary = ButlerColorsGreen.primaryDarkMediumContrast,
        onPrimary = ButlerColorsGreen.onPrimaryDarkMediumContrast,
        primaryContainer = ButlerColorsGreen.primaryContainerDarkMediumContrast,
        onPrimaryContainer = ButlerColorsGreen.onPrimaryContainerDarkMediumContrast,
        secondary = ButlerColorsGreen.secondaryDarkMediumContrast,
        onSecondary = ButlerColorsGreen.onSecondaryDarkMediumContrast,
        secondaryContainer = ButlerColorsGreen.secondaryContainerDarkMediumContrast,
        onSecondaryContainer = ButlerColorsGreen.onSecondaryContainerDarkMediumContrast,
        tertiary = ButlerColorsGreen.tertiaryDarkMediumContrast,
        onTertiary = ButlerColorsGreen.onTertiaryDarkMediumContrast,
        tertiaryContainer = ButlerColorsGreen.tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = ButlerColorsGreen.onTertiaryContainerDarkMediumContrast,
        error = ButlerColorsGreen.errorDarkMediumContrast,
        onError = ButlerColorsGreen.onErrorDarkMediumContrast,
        errorContainer = ButlerColorsGreen.errorContainerDarkMediumContrast,
        onErrorContainer = ButlerColorsGreen.onErrorContainerDarkMediumContrast,
        background = ButlerColorsGreen.backgroundDarkMediumContrast,
        onBackground = ButlerColorsGreen.onBackgroundDarkMediumContrast,
        surface = ButlerColorsGreen.surfaceDarkMediumContrast,
        onSurface = ButlerColorsGreen.onSurfaceDarkMediumContrast,
        surfaceVariant = ButlerColorsGreen.surfaceVariantDarkMediumContrast,
        onSurfaceVariant = ButlerColorsGreen.onSurfaceVariantDarkMediumContrast,
        outline = ButlerColorsGreen.outlineDarkMediumContrast,
        outlineVariant = ButlerColorsGreen.outlineVariantDarkMediumContrast,
        scrim = ButlerColorsGreen.scrimDarkMediumContrast,
        inverseSurface = ButlerColorsGreen.inverseSurfaceDarkMediumContrast,
        inverseOnSurface = ButlerColorsGreen.inverseOnSurfaceDarkMediumContrast,
        inversePrimary = ButlerColorsGreen.inversePrimaryDarkMediumContrast,
    )

    private fun getGreenHighContrastLightScheme() = lightColorScheme(
        primary = ButlerColorsGreen.primaryLightHighContrast,
        onPrimary = ButlerColorsGreen.onPrimaryLightHighContrast,
        primaryContainer = ButlerColorsGreen.primaryContainerLightHighContrast,
        onPrimaryContainer = ButlerColorsGreen.onPrimaryContainerLightHighContrast,
        secondary = ButlerColorsGreen.secondaryLightHighContrast,
        onSecondary = ButlerColorsGreen.onSecondaryLightHighContrast,
        secondaryContainer = ButlerColorsGreen.secondaryContainerLightHighContrast,
        onSecondaryContainer = ButlerColorsGreen.onSecondaryContainerLightHighContrast,
        tertiary = ButlerColorsGreen.tertiaryLightHighContrast,
        onTertiary = ButlerColorsGreen.onTertiaryLightHighContrast,
        tertiaryContainer = ButlerColorsGreen.tertiaryContainerLightHighContrast,
        onTertiaryContainer = ButlerColorsGreen.onTertiaryContainerLightHighContrast,
        error = ButlerColorsGreen.errorLightHighContrast,
        onError = ButlerColorsGreen.onErrorLightHighContrast,
        errorContainer = ButlerColorsGreen.errorContainerLightHighContrast,
        onErrorContainer = ButlerColorsGreen.onErrorContainerLightHighContrast,
        background = ButlerColorsGreen.backgroundLightHighContrast,
        onBackground = ButlerColorsGreen.onBackgroundLightHighContrast,
        surface = ButlerColorsGreen.surfaceLightHighContrast,
        onSurface = ButlerColorsGreen.onSurfaceLightHighContrast,
        surfaceVariant = ButlerColorsGreen.surfaceVariantLightHighContrast,
        onSurfaceVariant = ButlerColorsGreen.onSurfaceVariantLightHighContrast,
        outline = ButlerColorsGreen.outlineLightHighContrast,
        outlineVariant = ButlerColorsGreen.outlineVariantLightHighContrast,
        scrim = ButlerColorsGreen.scrimLightHighContrast,
        inverseSurface = ButlerColorsGreen.inverseSurfaceLightHighContrast,
        inverseOnSurface = ButlerColorsGreen.inverseOnSurfaceLightHighContrast,
        inversePrimary = ButlerColorsGreen.inversePrimaryLightHighContrast,
    )

    private fun getGreenHighContrastDarkScheme() = darkColorScheme(
        primary = ButlerColorsGreen.primaryDarkHighContrast,
        onPrimary = ButlerColorsGreen.onPrimaryDarkHighContrast,
        primaryContainer = ButlerColorsGreen.primaryContainerDarkHighContrast,
        onPrimaryContainer = ButlerColorsGreen.onPrimaryContainerDarkHighContrast,
        secondary = ButlerColorsGreen.secondaryDarkHighContrast,
        onSecondary = ButlerColorsGreen.onSecondaryDarkHighContrast,
        secondaryContainer = ButlerColorsGreen.secondaryContainerDarkHighContrast,
        onSecondaryContainer = ButlerColorsGreen.onSecondaryContainerDarkHighContrast,
        tertiary = ButlerColorsGreen.tertiaryDarkHighContrast,
        onTertiary = ButlerColorsGreen.onTertiaryDarkHighContrast,
        tertiaryContainer = ButlerColorsGreen.tertiaryContainerDarkHighContrast,
        onTertiaryContainer = ButlerColorsGreen.onTertiaryContainerDarkHighContrast,
        error = ButlerColorsGreen.errorDarkHighContrast,
        onError = ButlerColorsGreen.onErrorDarkHighContrast,
        errorContainer = ButlerColorsGreen.errorContainerDarkHighContrast,
        onErrorContainer = ButlerColorsGreen.onErrorContainerDarkHighContrast,
        background = ButlerColorsGreen.backgroundDarkHighContrast,
        onBackground = ButlerColorsGreen.onBackgroundDarkHighContrast,
        surface = ButlerColorsGreen.surfaceDarkHighContrast,
        onSurface = ButlerColorsGreen.onSurfaceDarkHighContrast,
        surfaceVariant = ButlerColorsGreen.surfaceVariantDarkHighContrast,
        onSurfaceVariant = ButlerColorsGreen.onSurfaceVariantDarkHighContrast,
        outline = ButlerColorsGreen.outlineDarkHighContrast,
        outlineVariant = ButlerColorsGreen.outlineVariantDarkHighContrast,
        scrim = ButlerColorsGreen.scrimDarkHighContrast,
        inverseSurface = ButlerColorsGreen.inverseSurfaceDarkHighContrast,
        inverseOnSurface = ButlerColorsGreen.inverseOnSurfaceDarkHighContrast,
        inversePrimary = ButlerColorsGreen.inversePrimaryDarkHighContrast,
    )

    // Blue color schemes
    private fun getBlueLightScheme() = lightColorScheme(
        primary = ButlerColorsBlue.primaryLight,
        onPrimary = ButlerColorsBlue.onPrimaryLight,
        primaryContainer = ButlerColorsBlue.primaryContainerLight,
        onPrimaryContainer = ButlerColorsBlue.onPrimaryContainerLight,
        secondary = ButlerColorsBlue.secondaryLight,
        onSecondary = ButlerColorsBlue.onSecondaryLight,
        secondaryContainer = ButlerColorsBlue.secondaryContainerLight,
        onSecondaryContainer = ButlerColorsBlue.onSecondaryContainerLight,
        tertiary = ButlerColorsBlue.tertiaryLight,
        onTertiary = ButlerColorsBlue.onTertiaryLight,
        tertiaryContainer = ButlerColorsBlue.tertiaryContainerLight,
        onTertiaryContainer = ButlerColorsBlue.onTertiaryContainerLight,
        error = ButlerColorsBlue.errorLight,
        onError = ButlerColorsBlue.onErrorLight,
        errorContainer = ButlerColorsBlue.errorContainerLight,
        onErrorContainer = ButlerColorsBlue.onErrorContainerLight,
        background = ButlerColorsBlue.backgroundLight,
        onBackground = ButlerColorsBlue.onBackgroundLight,
        surface = ButlerColorsBlue.surfaceLight,
        onSurface = ButlerColorsBlue.onSurfaceLight,
        surfaceVariant = ButlerColorsBlue.surfaceVariantLight,
        onSurfaceVariant = ButlerColorsBlue.onSurfaceVariantLight,
        outline = ButlerColorsBlue.outlineLight,
        outlineVariant = ButlerColorsBlue.outlineVariantLight,
        scrim = ButlerColorsBlue.scrimLight,
        inverseSurface = ButlerColorsBlue.inverseSurfaceLight,
        inverseOnSurface = ButlerColorsBlue.inverseOnSurfaceLight,
        inversePrimary = ButlerColorsBlue.inversePrimaryLight,
    )

    private fun getBlueDarkScheme() = darkColorScheme(
        primary = ButlerColorsBlue.primaryDark,
        onPrimary = ButlerColorsBlue.onPrimaryDark,
        primaryContainer = ButlerColorsBlue.primaryContainerDark,
        onPrimaryContainer = ButlerColorsBlue.onPrimaryContainerDark,
        secondary = ButlerColorsBlue.secondaryDark,
        onSecondary = ButlerColorsBlue.onSecondaryDark,
        secondaryContainer = ButlerColorsBlue.secondaryContainerDark,
        onSecondaryContainer = ButlerColorsBlue.onSecondaryContainerDark,
        tertiary = ButlerColorsBlue.tertiaryDark,
        onTertiary = ButlerColorsBlue.onTertiaryDark,
        tertiaryContainer = ButlerColorsBlue.tertiaryContainerDark,
        onTertiaryContainer = ButlerColorsBlue.onTertiaryContainerDark,
        error = ButlerColorsBlue.errorDark,
        onError = ButlerColorsBlue.onErrorDark,
        errorContainer = ButlerColorsBlue.errorContainerDark,
        onErrorContainer = ButlerColorsBlue.onErrorContainerDark,
        background = ButlerColorsBlue.backgroundDark,
        onBackground = ButlerColorsBlue.onBackgroundDark,
        surface = ButlerColorsBlue.surfaceDark,
        onSurface = ButlerColorsBlue.onSurfaceDark,
        surfaceVariant = ButlerColorsBlue.surfaceVariantDark,
        onSurfaceVariant = ButlerColorsBlue.onSurfaceVariantDark,
        outline = ButlerColorsBlue.outlineDark,
        outlineVariant = ButlerColorsBlue.outlineVariantDark,
        scrim = ButlerColorsBlue.scrimDark,
        inverseSurface = ButlerColorsBlue.inverseSurfaceDark,
        inverseOnSurface = ButlerColorsBlue.inverseOnSurfaceDark,
        inversePrimary = ButlerColorsBlue.inversePrimaryDark,
    )

    private fun getBlueMediumContrastLightScheme() = lightColorScheme(
        primary = ButlerColorsBlue.primaryLightMediumContrast,
        onPrimary = ButlerColorsBlue.onPrimaryLightMediumContrast,
        primaryContainer = ButlerColorsBlue.primaryContainerLightMediumContrast,
        onPrimaryContainer = ButlerColorsBlue.onPrimaryContainerLightMediumContrast,
        secondary = ButlerColorsBlue.secondaryLightMediumContrast,
        onSecondary = ButlerColorsBlue.onSecondaryLightMediumContrast,
        secondaryContainer = ButlerColorsBlue.secondaryContainerLightMediumContrast,
        onSecondaryContainer = ButlerColorsBlue.onSecondaryContainerLightMediumContrast,
        tertiary = ButlerColorsBlue.tertiaryLightMediumContrast,
        onTertiary = ButlerColorsBlue.onTertiaryLightMediumContrast,
        tertiaryContainer = ButlerColorsBlue.tertiaryContainerLightMediumContrast,
        onTertiaryContainer = ButlerColorsBlue.onTertiaryContainerLightMediumContrast,
        error = ButlerColorsBlue.errorLightMediumContrast,
        onError = ButlerColorsBlue.onErrorLightMediumContrast,
        errorContainer = ButlerColorsBlue.errorContainerLightMediumContrast,
        onErrorContainer = ButlerColorsBlue.onErrorContainerLightMediumContrast,
        background = ButlerColorsBlue.backgroundLightMediumContrast,
        onBackground = ButlerColorsBlue.onBackgroundLightMediumContrast,
        surface = ButlerColorsBlue.surfaceLightMediumContrast,
        onSurface = ButlerColorsBlue.onSurfaceLightMediumContrast,
        surfaceVariant = ButlerColorsBlue.surfaceVariantLightMediumContrast,
        onSurfaceVariant = ButlerColorsBlue.onSurfaceVariantLightMediumContrast,
        outline = ButlerColorsBlue.outlineLightMediumContrast,
        outlineVariant = ButlerColorsBlue.outlineVariantLightMediumContrast,
        scrim = ButlerColorsBlue.scrimLightMediumContrast,
        inverseSurface = ButlerColorsBlue.inverseSurfaceLightMediumContrast,
        inverseOnSurface = ButlerColorsBlue.inverseOnSurfaceLightMediumContrast,
        inversePrimary = ButlerColorsBlue.inversePrimaryLightMediumContrast,
    )

    private fun getBlueMediumContrastDarkScheme() = darkColorScheme(
        primary = ButlerColorsBlue.primaryDarkMediumContrast,
        onPrimary = ButlerColorsBlue.onPrimaryDarkMediumContrast,
        primaryContainer = ButlerColorsBlue.primaryContainerDarkMediumContrast,
        onPrimaryContainer = ButlerColorsBlue.onPrimaryContainerDarkMediumContrast,
        secondary = ButlerColorsBlue.secondaryDarkMediumContrast,
        onSecondary = ButlerColorsBlue.onSecondaryDarkMediumContrast,
        secondaryContainer = ButlerColorsBlue.secondaryContainerDarkMediumContrast,
        onSecondaryContainer = ButlerColorsBlue.onSecondaryContainerDarkMediumContrast,
        tertiary = ButlerColorsBlue.tertiaryDarkMediumContrast,
        onTertiary = ButlerColorsBlue.onTertiaryDarkMediumContrast,
        tertiaryContainer = ButlerColorsBlue.tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = ButlerColorsBlue.onTertiaryContainerDarkMediumContrast,
        error = ButlerColorsBlue.errorDarkMediumContrast,
        onError = ButlerColorsBlue.onErrorDarkMediumContrast,
        errorContainer = ButlerColorsBlue.errorContainerDarkMediumContrast,
        onErrorContainer = ButlerColorsBlue.onErrorContainerDarkMediumContrast,
        background = ButlerColorsBlue.backgroundDarkMediumContrast,
        onBackground = ButlerColorsBlue.onBackgroundDarkMediumContrast,
        surface = ButlerColorsBlue.surfaceDarkMediumContrast,
        onSurface = ButlerColorsBlue.onSurfaceDarkMediumContrast,
        surfaceVariant = ButlerColorsBlue.surfaceVariantDarkMediumContrast,
        onSurfaceVariant = ButlerColorsBlue.onSurfaceVariantDarkMediumContrast,
        outline = ButlerColorsBlue.outlineDarkMediumContrast,
        outlineVariant = ButlerColorsBlue.outlineVariantDarkMediumContrast,
        scrim = ButlerColorsBlue.scrimDarkMediumContrast,
        inverseSurface = ButlerColorsBlue.inverseSurfaceDarkMediumContrast,
        inverseOnSurface = ButlerColorsBlue.inverseOnSurfaceDarkMediumContrast,
        inversePrimary = ButlerColorsBlue.inversePrimaryDarkMediumContrast,
    )

    private fun getBlueHighContrastLightScheme() = lightColorScheme(
        primary = ButlerColorsBlue.primaryLightHighContrast,
        onPrimary = ButlerColorsBlue.onPrimaryLightHighContrast,
        primaryContainer = ButlerColorsBlue.primaryContainerLightHighContrast,
        onPrimaryContainer = ButlerColorsBlue.onPrimaryContainerLightHighContrast,
        secondary = ButlerColorsBlue.secondaryLightHighContrast,
        onSecondary = ButlerColorsBlue.onSecondaryLightHighContrast,
        secondaryContainer = ButlerColorsBlue.secondaryContainerLightHighContrast,
        onSecondaryContainer = ButlerColorsBlue.onSecondaryContainerLightHighContrast,
        tertiary = ButlerColorsBlue.tertiaryLightHighContrast,
        onTertiary = ButlerColorsBlue.onTertiaryLightHighContrast,
        tertiaryContainer = ButlerColorsBlue.tertiaryContainerLightHighContrast,
        onTertiaryContainer = ButlerColorsBlue.onTertiaryContainerLightHighContrast,
        error = ButlerColorsBlue.errorLightHighContrast,
        onError = ButlerColorsBlue.onErrorLightHighContrast,
        errorContainer = ButlerColorsBlue.errorContainerLightHighContrast,
        onErrorContainer = ButlerColorsBlue.onErrorContainerLightHighContrast,
        background = ButlerColorsBlue.backgroundLightHighContrast,
        onBackground = ButlerColorsBlue.onBackgroundLightHighContrast,
        surface = ButlerColorsBlue.surfaceLightHighContrast,
        onSurface = ButlerColorsBlue.onSurfaceLightHighContrast,
        surfaceVariant = ButlerColorsBlue.surfaceVariantLightHighContrast,
        onSurfaceVariant = ButlerColorsBlue.onSurfaceVariantLightHighContrast,
        outline = ButlerColorsBlue.outlineLightHighContrast,
        outlineVariant = ButlerColorsBlue.outlineVariantLightHighContrast,
        scrim = ButlerColorsBlue.scrimLightHighContrast,
        inverseSurface = ButlerColorsBlue.inverseSurfaceLightHighContrast,
        inverseOnSurface = ButlerColorsBlue.inverseOnSurfaceLightHighContrast,
        inversePrimary = ButlerColorsBlue.inversePrimaryLightHighContrast,
    )

    private fun getBlueHighContrastDarkScheme() = darkColorScheme(
        primary = ButlerColorsBlue.primaryDarkHighContrast,
        onPrimary = ButlerColorsBlue.onPrimaryDarkHighContrast,
        primaryContainer = ButlerColorsBlue.primaryContainerDarkHighContrast,
        onPrimaryContainer = ButlerColorsBlue.onPrimaryContainerDarkHighContrast,
        secondary = ButlerColorsBlue.secondaryDarkHighContrast,
        onSecondary = ButlerColorsBlue.onSecondaryDarkHighContrast,
        secondaryContainer = ButlerColorsBlue.secondaryContainerDarkHighContrast,
        onSecondaryContainer = ButlerColorsBlue.onSecondaryContainerDarkHighContrast,
        tertiary = ButlerColorsBlue.tertiaryDarkHighContrast,
        onTertiary = ButlerColorsBlue.onTertiaryDarkHighContrast,
        tertiaryContainer = ButlerColorsBlue.tertiaryContainerDarkHighContrast,
        onTertiaryContainer = ButlerColorsBlue.onTertiaryContainerDarkHighContrast,
        error = ButlerColorsBlue.errorDarkHighContrast,
        onError = ButlerColorsBlue.onErrorDarkHighContrast,
        errorContainer = ButlerColorsBlue.errorContainerDarkHighContrast,
        onErrorContainer = ButlerColorsBlue.onErrorContainerDarkHighContrast,
        background = ButlerColorsBlue.backgroundDarkHighContrast,
        onBackground = ButlerColorsBlue.onBackgroundDarkHighContrast,
        surface = ButlerColorsBlue.surfaceDarkHighContrast,
        onSurface = ButlerColorsBlue.onSurfaceDarkHighContrast,
        surfaceVariant = ButlerColorsBlue.surfaceVariantDarkHighContrast,
        onSurfaceVariant = ButlerColorsBlue.onSurfaceVariantDarkHighContrast,
        outline = ButlerColorsBlue.outlineDarkHighContrast,
        outlineVariant = ButlerColorsBlue.outlineVariantDarkHighContrast,
        scrim = ButlerColorsBlue.scrimDarkHighContrast,
        inverseSurface = ButlerColorsBlue.inverseSurfaceDarkHighContrast,
        inverseOnSurface = ButlerColorsBlue.inverseOnSurfaceDarkHighContrast,
        inversePrimary = ButlerColorsBlue.inversePrimaryDarkHighContrast,
    )

    // AMOLED color schemes
    private fun getAmoledLightScheme() = lightColorScheme(
        primary = ButlerColorsAmoled.primaryLight,
        onPrimary = ButlerColorsAmoled.onPrimaryLight,
        primaryContainer = ButlerColorsAmoled.primaryContainerLight,
        onPrimaryContainer = ButlerColorsAmoled.onPrimaryContainerLight,
        secondary = ButlerColorsAmoled.secondaryLight,
        onSecondary = ButlerColorsAmoled.onSecondaryLight,
        secondaryContainer = ButlerColorsAmoled.secondaryContainerLight,
        onSecondaryContainer = ButlerColorsAmoled.onSecondaryContainerLight,
        tertiary = ButlerColorsAmoled.tertiaryLight,
        onTertiary = ButlerColorsAmoled.onTertiaryLight,
        tertiaryContainer = ButlerColorsAmoled.tertiaryContainerLight,
        onTertiaryContainer = ButlerColorsAmoled.onTertiaryContainerLight,
        error = ButlerColorsAmoled.errorLight,
        onError = ButlerColorsAmoled.onErrorLight,
        errorContainer = ButlerColorsAmoled.errorContainerLight,
        onErrorContainer = ButlerColorsAmoled.onErrorContainerLight,
        background = ButlerColorsAmoled.backgroundLight,
        onBackground = ButlerColorsAmoled.onBackgroundLight,
        surface = ButlerColorsAmoled.surfaceLight,
        onSurface = ButlerColorsAmoled.onSurfaceLight,
        surfaceVariant = ButlerColorsAmoled.surfaceVariantLight,
        onSurfaceVariant = ButlerColorsAmoled.onSurfaceVariantLight,
        outline = ButlerColorsAmoled.outlineLight,
        outlineVariant = ButlerColorsAmoled.outlineVariantLight,
        scrim = ButlerColorsAmoled.scrimLight,
        inverseSurface = ButlerColorsAmoled.inverseSurfaceLight,
        inverseOnSurface = ButlerColorsAmoled.inverseOnSurfaceLight,
        inversePrimary = ButlerColorsAmoled.inversePrimaryLight,
    )

    private fun getAmoledDarkScheme() = darkColorScheme(
        primary = ButlerColorsAmoled.primaryDark,
        onPrimary = ButlerColorsAmoled.onPrimaryDark,
        primaryContainer = ButlerColorsAmoled.primaryContainerDark,
        onPrimaryContainer = ButlerColorsAmoled.onPrimaryContainerDark,
        secondary = ButlerColorsAmoled.secondaryDark,
        onSecondary = ButlerColorsAmoled.onSecondaryDark,
        secondaryContainer = ButlerColorsAmoled.secondaryContainerDark,
        onSecondaryContainer = ButlerColorsAmoled.onSecondaryContainerDark,
        tertiary = ButlerColorsAmoled.tertiaryDark,
        onTertiary = ButlerColorsAmoled.onTertiaryDark,
        tertiaryContainer = ButlerColorsAmoled.tertiaryContainerDark,
        onTertiaryContainer = ButlerColorsAmoled.onTertiaryContainerDark,
        error = ButlerColorsAmoled.errorDark,
        onError = ButlerColorsAmoled.onErrorDark,
        errorContainer = ButlerColorsAmoled.errorContainerDark,
        onErrorContainer = ButlerColorsAmoled.onErrorContainerDark,
        background = ButlerColorsAmoled.backgroundDark,
        onBackground = ButlerColorsAmoled.onBackgroundDark,
        surface = ButlerColorsAmoled.surfaceDark,
        onSurface = ButlerColorsAmoled.onSurfaceDark,
        surfaceVariant = ButlerColorsAmoled.surfaceVariantDark,
        onSurfaceVariant = ButlerColorsAmoled.onSurfaceVariantDark,
        outline = ButlerColorsAmoled.outlineDark,
        outlineVariant = ButlerColorsAmoled.outlineVariantDark,
        scrim = ButlerColorsAmoled.scrimDark,
        inverseSurface = ButlerColorsAmoled.inverseSurfaceDark,
        inverseOnSurface = ButlerColorsAmoled.inverseOnSurfaceDark,
        inversePrimary = ButlerColorsAmoled.inversePrimaryDark,
    )

    private fun getAmoledMediumContrastLightScheme() = lightColorScheme(
        primary = ButlerColorsAmoled.primaryLightMediumContrast,
        onPrimary = ButlerColorsAmoled.onPrimaryLightMediumContrast,
        primaryContainer = ButlerColorsAmoled.primaryContainerLightMediumContrast,
        onPrimaryContainer = ButlerColorsAmoled.onPrimaryContainerLightMediumContrast,
        secondary = ButlerColorsAmoled.secondaryLightMediumContrast,
        onSecondary = ButlerColorsAmoled.onSecondaryLightMediumContrast,
        secondaryContainer = ButlerColorsAmoled.secondaryContainerLightMediumContrast,
        onSecondaryContainer = ButlerColorsAmoled.onSecondaryContainerLightMediumContrast,
        tertiary = ButlerColorsAmoled.tertiaryLightMediumContrast,
        onTertiary = ButlerColorsAmoled.onTertiaryLightMediumContrast,
        tertiaryContainer = ButlerColorsAmoled.tertiaryContainerLightMediumContrast,
        onTertiaryContainer = ButlerColorsAmoled.onTertiaryContainerLightMediumContrast,
        error = ButlerColorsAmoled.errorLightMediumContrast,
        onError = ButlerColorsAmoled.onErrorLightMediumContrast,
        errorContainer = ButlerColorsAmoled.errorContainerLightMediumContrast,
        onErrorContainer = ButlerColorsAmoled.onErrorContainerLightMediumContrast,
        background = ButlerColorsAmoled.backgroundLightMediumContrast,
        onBackground = ButlerColorsAmoled.onBackgroundLightMediumContrast,
        surface = ButlerColorsAmoled.surfaceLightMediumContrast,
        onSurface = ButlerColorsAmoled.onSurfaceLightMediumContrast,
        surfaceVariant = ButlerColorsAmoled.surfaceVariantLightMediumContrast,
        onSurfaceVariant = ButlerColorsAmoled.onSurfaceVariantLightMediumContrast,
        outline = ButlerColorsAmoled.outlineLightMediumContrast,
        outlineVariant = ButlerColorsAmoled.outlineVariantLightMediumContrast,
        scrim = ButlerColorsAmoled.scrimLightMediumContrast,
        inverseSurface = ButlerColorsAmoled.inverseSurfaceLightMediumContrast,
        inverseOnSurface = ButlerColorsAmoled.inverseOnSurfaceLightMediumContrast,
        inversePrimary = ButlerColorsAmoled.inversePrimaryLightMediumContrast,
    )

    private fun getAmoledMediumContrastDarkScheme() = darkColorScheme(
        primary = ButlerColorsAmoled.primaryDarkMediumContrast,
        onPrimary = ButlerColorsAmoled.onPrimaryDarkMediumContrast,
        primaryContainer = ButlerColorsAmoled.primaryContainerDarkMediumContrast,
        onPrimaryContainer = ButlerColorsAmoled.onPrimaryContainerDarkMediumContrast,
        secondary = ButlerColorsAmoled.secondaryDarkMediumContrast,
        onSecondary = ButlerColorsAmoled.onSecondaryDarkMediumContrast,
        secondaryContainer = ButlerColorsAmoled.secondaryContainerDarkMediumContrast,
        onSecondaryContainer = ButlerColorsAmoled.onSecondaryContainerDarkMediumContrast,
        tertiary = ButlerColorsAmoled.tertiaryDarkMediumContrast,
        onTertiary = ButlerColorsAmoled.onTertiaryDarkMediumContrast,
        tertiaryContainer = ButlerColorsAmoled.tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = ButlerColorsAmoled.onTertiaryContainerDarkMediumContrast,
        error = ButlerColorsAmoled.errorDarkMediumContrast,
        onError = ButlerColorsAmoled.onErrorDarkMediumContrast,
        errorContainer = ButlerColorsAmoled.errorContainerDarkMediumContrast,
        onErrorContainer = ButlerColorsAmoled.onErrorContainerDarkMediumContrast,
        background = ButlerColorsAmoled.backgroundDarkMediumContrast,
        onBackground = ButlerColorsAmoled.onBackgroundDarkMediumContrast,
        surface = ButlerColorsAmoled.surfaceDarkMediumContrast,
        onSurface = ButlerColorsAmoled.onSurfaceDarkMediumContrast,
        surfaceVariant = ButlerColorsAmoled.surfaceVariantDarkMediumContrast,
        onSurfaceVariant = ButlerColorsAmoled.onSurfaceVariantDarkMediumContrast,
        outline = ButlerColorsAmoled.outlineDarkMediumContrast,
        outlineVariant = ButlerColorsAmoled.outlineVariantDarkMediumContrast,
        scrim = ButlerColorsAmoled.scrimDarkMediumContrast,
        inverseSurface = ButlerColorsAmoled.inverseSurfaceDarkMediumContrast,
        inverseOnSurface = ButlerColorsAmoled.inverseOnSurfaceDarkMediumContrast,
        inversePrimary = ButlerColorsAmoled.inversePrimaryDarkMediumContrast,
    )

    private fun getAmoledHighContrastLightScheme() = lightColorScheme(
        primary = ButlerColorsAmoled.primaryLightHighContrast,
        onPrimary = ButlerColorsAmoled.onPrimaryLightHighContrast,
        primaryContainer = ButlerColorsAmoled.primaryContainerLightHighContrast,
        onPrimaryContainer = ButlerColorsAmoled.onPrimaryContainerLightHighContrast,
        secondary = ButlerColorsAmoled.secondaryLightHighContrast,
        onSecondary = ButlerColorsAmoled.onSecondaryLightHighContrast,
        secondaryContainer = ButlerColorsAmoled.secondaryContainerLightHighContrast,
        onSecondaryContainer = ButlerColorsAmoled.onSecondaryContainerLightHighContrast,
        tertiary = ButlerColorsAmoled.tertiaryLightHighContrast,
        onTertiary = ButlerColorsAmoled.onTertiaryLightHighContrast,
        tertiaryContainer = ButlerColorsAmoled.tertiaryContainerLightHighContrast,
        onTertiaryContainer = ButlerColorsAmoled.onTertiaryContainerLightHighContrast,
        error = ButlerColorsAmoled.errorLightHighContrast,
        onError = ButlerColorsAmoled.onErrorLightHighContrast,
        errorContainer = ButlerColorsAmoled.errorContainerLightHighContrast,
        onErrorContainer = ButlerColorsAmoled.onErrorContainerLightHighContrast,
        background = ButlerColorsAmoled.backgroundLightHighContrast,
        onBackground = ButlerColorsAmoled.onBackgroundLightHighContrast,
        surface = ButlerColorsAmoled.surfaceLightHighContrast,
        onSurface = ButlerColorsAmoled.onSurfaceLightHighContrast,
        surfaceVariant = ButlerColorsAmoled.surfaceVariantLightHighContrast,
        onSurfaceVariant = ButlerColorsAmoled.onSurfaceVariantLightHighContrast,
        outline = ButlerColorsAmoled.outlineLightHighContrast,
        outlineVariant = ButlerColorsAmoled.outlineVariantLightHighContrast,
        scrim = ButlerColorsAmoled.scrimLightHighContrast,
        inverseSurface = ButlerColorsAmoled.inverseSurfaceLightHighContrast,
        inverseOnSurface = ButlerColorsAmoled.inverseOnSurfaceLightHighContrast,
        inversePrimary = ButlerColorsAmoled.inversePrimaryLightHighContrast,
    )

    private fun getAmoledHighContrastDarkScheme() = darkColorScheme(
        primary = ButlerColorsAmoled.primaryDarkHighContrast,
        onPrimary = ButlerColorsAmoled.onPrimaryDarkHighContrast,
        primaryContainer = ButlerColorsAmoled.primaryContainerDarkHighContrast,
        onPrimaryContainer = ButlerColorsAmoled.onPrimaryContainerDarkHighContrast,
        secondary = ButlerColorsAmoled.secondaryDarkHighContrast,
        onSecondary = ButlerColorsAmoled.onSecondaryDarkHighContrast,
        secondaryContainer = ButlerColorsAmoled.secondaryContainerDarkHighContrast,
        onSecondaryContainer = ButlerColorsAmoled.onSecondaryContainerDarkHighContrast,
        tertiary = ButlerColorsAmoled.tertiaryDarkHighContrast,
        onTertiary = ButlerColorsAmoled.onTertiaryDarkHighContrast,
        tertiaryContainer = ButlerColorsAmoled.tertiaryContainerDarkHighContrast,
        onTertiaryContainer = ButlerColorsAmoled.onTertiaryContainerDarkHighContrast,
        error = ButlerColorsAmoled.errorDarkHighContrast,
        onError = ButlerColorsAmoled.onErrorDarkHighContrast,
        errorContainer = ButlerColorsAmoled.errorContainerDarkHighContrast,
        onErrorContainer = ButlerColorsAmoled.onErrorContainerDarkHighContrast,
        background = ButlerColorsAmoled.backgroundDarkHighContrast,
        onBackground = ButlerColorsAmoled.onBackgroundDarkHighContrast,
        surface = ButlerColorsAmoled.surfaceDarkHighContrast,
        onSurface = ButlerColorsAmoled.onSurfaceDarkHighContrast,
        surfaceVariant = ButlerColorsAmoled.surfaceVariantDarkHighContrast,
        onSurfaceVariant = ButlerColorsAmoled.onSurfaceVariantDarkHighContrast,
        outline = ButlerColorsAmoled.outlineDarkHighContrast,
        outlineVariant = ButlerColorsAmoled.outlineVariantDarkHighContrast,
        scrim = ButlerColorsAmoled.scrimDarkHighContrast,
        inverseSurface = ButlerColorsAmoled.inverseSurfaceDarkHighContrast,
        inverseOnSurface = ButlerColorsAmoled.inverseOnSurfaceDarkHighContrast,
        inversePrimary = ButlerColorsAmoled.inversePrimaryDarkHighContrast,
    )
}