package eu.darken.butler.screenshots

import androidx.compose.ui.tooling.preview.Preview

/**
 * Locale previews rendered on the phone device spec.
 *
 * The three annotation classes below differ only in the device spec they pin - the form factor of a
 * screenshot comes from the test function that carries the annotation, never from the preview
 * [name]. [name] stays the plain fastlane metadata directory so the copy script can keep reading
 * the locale straight out of the file name.
 *
 * Generated by `fastlane/generate_screenshots.sh`; the checked-in state is en-US only.
 */
@Preview(locale = "en", name = "en-US", device = DS_PHONE, showSystemUi = true)
annotation class PlayStoreLocalesPhone

/** Locale previews rendered on the 7" tablet device spec. See [PlayStoreLocalesPhone]. */
@Preview(locale = "en", name = "en-US", device = DS_SEVEN, showSystemUi = true)
annotation class PlayStoreLocalesSeven

/** Locale previews rendered on the 10" tablet device spec. See [PlayStoreLocalesPhone]. */
@Preview(locale = "en", name = "en-US", device = DS_TEN, showSystemUi = true)
annotation class PlayStoreLocalesTen
