theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-github-metadata
  - jemoji

relative_links:
  enabled: true
  collections: true

title: "Butler"
description: "The file explorer for Android."
author: "by Matthias Urhahn"

header_pages:
  - CHANGELOG.md
  - PRIVACY_POLICY.md
  - SECURITY.md

include:
  - PRIVACY_POLICY.md
exclude:
  - buildSrc
  - gradle/wrapper
  - fastlane
  - crowdin*
  - app
  - app-common
  - app-common-test
  - app-common-shell
  - app-common-root
  - app-common-pkgs
  - app-common-io
  - app-common-adb
  - motd
  - docs
  - tooling
  - CONTRIBUTING.md
