pluginManagement {
    repositories {
        google()
        gradlePluginPortal()
        mavenCentral()
        maven {
            url = uri("https://androidx.dev/snapshots/builds/13610170/artifacts/repository")
        }
    }
}

dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
        maven {
            url = uri("https://androidx.dev/snapshots/builds/13610170/artifacts/repository")
        }
    }
}

rootProject.name = "Butler"
include ':app'
include ':app-common-root'
include ':app-common'
include ':app-common-test'
include ':app-common-io'
include ':app-common-pkgs'
include ':app-common-shell'
include ':app-common-adb'
include ':app-workspace'
include ':app-workspace-explorer'
include ':app-workspace-searcher'
include ':app-workspace-editor'
include ':app-workspace-templates'
include ':app-workspace-apps'
include ':app-workspace-saver'
include ':app-workspace-developer'
include ':app-workspace-history'
include ':app-provider-documents'