name: Test Reports

on:
  workflow_run:
    workflows: [ 'Code tests & eval' ]
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: read

jobs:
  report:
    runs-on: ubuntu-22.04
    if: always()
    strategy:
      fail-fast: false
      matrix:
        # Must match the artifacts uploaded by the test-modules matrix in code-checks.yml
        variant: [ Debug ]
        flavor: [ test,testFoss,testGplay ]
    steps:
      - name: Test Report
        uses: dorny/test-reporter@a43b3a5f7366b97d083190328d2c652e1a8b6aa2 #v3.0.0
        if: always()
        with:
          name: 'Unit Tests - ${{ matrix.flavor }} ${{ matrix.variant }}'
          artifact: test-results-${{ matrix.flavor }}-${{ matrix.variant }}
          path: '**/*.xml'
          reporter: java-junit
          fail-on-error: false
          list-suites: 'failed'
          list-tests: 'failed'
          max-annotations: 10
